# "Ultimate Champion" Configuration for EEGNeX on 45Hz Data
# This file represents the single best model found after a multi-stage,
# comprehensive Optuna search.
# APPLIED TO: 3-class (1,2,3) landing digit task
# DATASET: all_trials_dataset (1-45hz)
# EVALUATION: Full Leave-One-Subject-Out (LOSO)

model_name: eegnex

# --- Data Loading ---
dataset_dir: "data_preprocessed/all_trials_dataset (1-45hz) V2"
use_channel_list: non_scalp # <-- Activate exclusion of non-scalp channels
# No n_folds key defaults the runner to full Leave-One-Subject-Out (LOSO)
crop_ms: [50, 250]

# --- Training (for final LOSO run) ---
epochs: 100
early_stop: 20
save_ckpt: true

# --- Hyperparameters from the Finalist Champion (Trial 142) ---
# Core Architecture
lr: 0.000781426
batch_size: 16
scheduler_patience: 14
filter_1: 16
kernel_block_1_2: 128
drop_prob: 0.474054223
depth_multiplier: 1

# Deeper Architecture
kernel_block_4: 24
dilation_block_4: 1
avg_pool_block4: 4
kernel_block_5: 8
dilation_block_5: 4
avg_pool_block5: 16

# Augmentations
mixup_alpha: 0.167943267
shift_p: 0.182100037
shift_max_frac: 0.039063018
scale_p: 0.081532162
scale_max: 1.14987267
noise_p: 0.087185426
noise_std: 0.020216591
time_mask_p: 0.340388497
time_mask_frac: 0.086952604
chan_mask_p: 0.332160404

# --- FIXED Base Model Parameters (from previous studies) ---
filter_2: 32
max_norm_conv: 1.0
max_norm_linear: 0.25
scale_min: 0.9
chan_mask_ratio: 0.05
