# Optuna search space for CNN baseline on dec1_5class

# --- optimiser ---
lr:
  method: log_uniform
  low: 1.0e-5
  high: 1.0e-3

weight_decay:
  method: log_uniform
  low: 1.0e-6
  high: 1.0e-2

# --- training hyper-params ---
batch_size:
  method: categorical
  choices: [32, 64]

# --- regularisation & augmentation ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.6

shift_p:
  method: uniform
  low: 0.5
  high: 1.0

scale_p:
  method: uniform
  low: 0.0
  high: 0.2

noise_std:
  method: uniform
  low: 0.0
  high: 0.05

time_mask_p:
  method: uniform
  low: 0.0
  high: 0.5

chan_mask_p:
  method: uniform
  low: 0.0
  high: 0.5 