# Hybrid defaults – 6-group split, 60 epochs

# Nominally identical to hybrid_base_nf6.yaml except epochs

# include: configs/inc1_5class/hybrid_base_nf6.yaml  # reference only; include not processed automatically

dataset_dir: data_preprocessed/acc_1_dataset

batch_size: 64
lr: 0.0003
epochs: 60
early_stop: 15
max_folds: null
n_folds: 6

# model specifics
enc_kernel: 7
latent_dim: 64
n_heads: 4
depth: 4
dropout: 0.1
enc_stride: 2

# augmentation
shift_p: 0.9771999065686038
shift_min_frac: 0.005
shift_max_frac: 0.04
scale_p: 0.08568568458523856
scale_min: 0.9
scale_max: 1.1
noise_p: 0.3
noise_std: 0.022713472820544915

mixup_alpha: 0.40991426550989196

time_mask_p: 0.22274360262040488
time_mask_frac: 0.15
chan_mask_p: 0.181364322319745
chan_mask_ratio: 0.10 