dataset_dir: data_preprocessed/acc_1_dataset

batch_size: 64
lr: 1e-4
epochs: 100
early_stop: 15

noise_std: 0.05
channel_dropout_p: 0.1

mixup_alpha: 0.0
time_mask_p: 0.0
time_mask_frac: 0.15
chan_mask_p: 0.0
chan_mask_ratio: 0.10 