# Default hyper-parameters for ViT landing-digit decoder
# Anything omitted falls back to the script-level DEFAULTS

# --- data ---
dataset_dir: data_spectrograms/landing_digit_cwt_128x128

# --- training ---
batch_size: 32
lr: 1e-4
weight_decay: 1e-5
epochs: 100
early_stop: 15
max_folds: 3      # override to None for full LOSO

# --- model ---
model_name: vit_relpos_medium_patch16_224
img_size: 128
dropout: 0.1
drop_path_rate: 0.1
attn_drop_rate: 0.0
token_drop_rate: 0.1  # mapped to timm 'drop_rate'
qkv_bias: true

# --- optimiser extras ---
betas: [0.9, 0.95]
min_lr: 1e-6
grad_clip_norm: 1.0

# --- loss ---
label_smoothing: 0.05

# --- augmentation ---
mixup_alpha: 0.2
time_mask_p: 0.3
time_mask_frac: 0.15
freq_mask_p: 0.3
freq_mask_frac: 0.15 