# Optuna search space for ViT landing-digit task
# key: {method: <uniform|log_uniform|categorical>, args: [low, high] or [choices]}

lr:
  method: log_uniform
  low: 1e-5
  high: 5e-4

weight_decay:
  method: log_uniform
  low: 1e-6
  high: 1e-2

model_name:
  method: categorical
  choices: [vit_tiny_patch16_224, vit_relpos_medium_patch16_224]

dropout:
  method: uniform
  low: 0.0
  high: 0.4

mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.6

time_mask_p:
  method: uniform
  low: 0.0
  high: 0.5

freq_mask_p:
  method: uniform
  low: 0.0
  high: 0.5 

# --- new ViT regulariser & optimisation params ---

drop_path_rate:
  method: uniform
  low: 0.0
  high: 0.25

attn_drop_rate:
  method: uniform
  low: 0.0
  high: 0.15

token_drop_rate:
  method: uniform
  low: 0.0
  high: 0.3

qkv_bias:
  method: categorical
  choices: [true, false]

label_smoothing:
  method: uniform
  low: 0.0
  high: 0.2

betas:
  method: uniform  # beta2 component only; beta1 fixed at 0.9
  low: 0.92
  high: 0.999

grad_clip_norm:
  method: categorical
  choices: [0.5, 1.0, 2.0]

min_lr:
  method: log_uniform
  low: 1e-7
  high: 5e-6 

# --- dataset & augmentation specifics not previously included ---

time_mask_frac:
  method: uniform
  low: 0.05
  high: 0.20

freq_mask_frac:
  method: uniform
  low: 0.05
  high: 0.20

# --- throughput tuning ---

num_workers:
  method: categorical
  choices: [8, 12] 