# EEGNeX on raw EEG (45 Hz) – Base config for the STAGE 3 Augmentation Search.
# This file FIXES the champion architecture from Stage 2 (Trial 268).
# It is designed to be used with optuna_space_eegnex_45hz_augmentations.yaml.

model_name: eegnex

# --- Data Loading ---
dataset_dir: "data_preprocessed/all_trials_dataset (45hz) V2"
n_folds: 4

# --- Training (for fast search) ---
epochs: 40
early_stop: 10

# --- FIXED Champion Architecture (from Stage 2, Trial 268) ---
lr: 0.000971212
batch_size: 16
scheduler_patience: 14
filter_1: 16
kernel_block_1_2: 128
drop_prob: 0.476060997
depth_multiplier: 1
kernel_block_4: 24
dilation_block_4: 1
avg_pool_block4: 4
kernel_block_5: 8
dilation_block_5: 8
avg_pool_block5: 16

# --- PLACEHOLDER Augmentations ---
# Optuna will overwrite these.
mixup_alpha: 0.2
shift_p: 0.5
shift_max_frac: 0.02
scale_p: 0.1
scale_max: 1.1
noise_p: 0.3
noise_std: 0.02
time_mask_p: 0.1
time_mask_frac: 0.1
chan_mask_p: 0.1

# --- FIXED Base Model Parameters ---
filter_2: 32
max_norm_conv: 1.0
max_norm_linear: 0.25
scale_min: 0.9
chan_mask_ratio: 0.05