# Optuna search space for EEGNeX 45Hz Data - STAGE 4: Finalist Study
# This is the final consolidated search. It tunes the MOST SENSITIVE parameters
# from all previous stages together to find the optimal interactions.

# --- Core Optimizer and Regularization ---
lr:
  method: log_uniform
  low: 7.0e-4
  high: 1.2e-3
drop_prob:
  method: uniform
  low: 0.3
  high: 0.7

# --- Deeper Architecture Fine-Tuning ---
kernel_block_5:
  method: categorical
  choices: [8, 16, 24]
dilation_block_5:
  method: categorical
  choices: [4, 8] # Top performers from Stage 2 used higher dilation.
avg_pool_block5:
  method: categorical
  choices: [8, 16] # Top performers from Stage 2 used higher pooling.

# --- Core Augmentation Parameters ---
mixup_alpha:
  method: uniform
  low: 0.1
  high: 0.4 # Refined range based on Stage 3 results.
time_mask_p:
  method: uniform
  low: 0.3
  high: 0.5 # Refined range based on Stage 3 results.
chan_mask_p:
  method: uniform
  low: 0.3
  high: 0.6 # Refined range based on Stage 3 results.