dataset_dir: data_preprocessed/acc_1_dataset

# training
batch_size: 64
lr: 0.001
epochs: 80
early_stop: 15
max_folds: null  # run all subjects

# augmentation
auto_lr: false  # manual LR tuning
shift_p: 0.8
shift_min_frac: 0.005
shift_max_frac: 0.04
scale_p: 0.1
scale_min: 0.9
scale_max: 1.1
noise_p: 0.3
noise_std: 0.02

# mixup & masking
mixup_alpha: 0.3
time_mask_p: 0.2
time_mask_frac: 0.15
chan_mask_p: 0.2
chan_mask_ratio: 0.10 