# Optuna search space – inc1_binary CNN

lr:
  method: log_uniform
  low: 1.0e-4      # start of plateau in previous runs
  high: 2.0e-3     # upper tested bound

weight_decay:
  method: log_uniform
  low: 1.0e-6
  high: 1.0e-2

# --- training ---
batch_size:
  method: categorical
  choices: [32, 64, 128]   # allow exploration; GPU fits both

# --- augmentation & regularisation ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.6

shift_p:
  method: uniform
  low: 0.5
  high: 1.0

scale_p:
  method: uniform
  low: 0.0
  high: 0.1

noise_std:
  method: uniform
  low: 0.0
  high: 0.05

time_mask_p:
  method: uniform
  low: 0.0
  high: 0.3

chan_mask_p:
  method: uniform
  low: 0.0
  high: 0.5 