dataset_dir: data_preprocessed/acc_1_dataset

# training
batch_size: 64
lr: 1e-4
epochs: 50
early_stop: 15
max_folds: null   # null means run all subjects

# augmentation
shift_p: 0.5
shift_min_frac: 0.005
shift_max_frac: 0.04
scale_p: 0.5
scale_min: 0.9
scale_max: 1.1
noise_p: 0.3
noise_std: 0.02 