# CNN baseline for landing_digit – uses ALL trials (incl. incorrect responses)
# Cloned from cnn_base.yaml; only dataset_dir differs.

dataset_dir: data_preprocessed/all_trials_dataset

# training
batch_size: 64
lr: 0.0009998821611575948
epochs: 100
early_stop: 15
max_folds: null   # null → run all subjects unless overridden by Optuna

# augmentation
shift_p: 0.9771999065686038
shift_min_frac: 0.005
shift_max_frac: 0.04
scale_p: 0.08568568458523856
scale_min: 0.9
scale_max: 1.1
noise_p: 0.3
noise_std: 0.022713472820544915

# mixup & masking
mixup_alpha: 0.40991426550989196

time_mask_p: 0.22274360262040488
time_mask_frac: 0.15
chan_mask_p: 0.181364322319745
chan_mask_ratio: 0.10 