# FILE: dual_stream_base_acc1_t048.yaml
# LOSO configuration for a top model from study landing_digit_dual_stream-acc1-nf4-03.
# Original Trial ID: 48
# Mean Accuracy (nf4): 26.93%

model_name: dual_stream

# --- Data Loading ---
dataset_dir_base: "data_dual_stream"
dataset_name: "acc_1_dataset"
spec_config_name: "64-8"
in_memory: true

# --- Training ---
batch_size: 16
lr: 0.000472055
epochs: 100
early_stop: 15
scheduler_patience: 10 # This was tuned

# --- Time-Series Stream (MultiScaleCNN) ---
ts_stream_config:
  kernel_sizes: [7, 11, 15, 19]
  F1: 4
  F2: 16 # This is the default, F2 = 2 * F1
  D: 6
  kernel_2: 16
  dropout: 0.438497323

# --- Spectrogram Stream (2D CNN) ---
spec_stream_config:
  arch: "resnet18"
  pretrained: true # ResNet will use pre-trained weights
  channels: [32, 64] # (Ignored for ResNet arch)
  dropout: 0.23737127806190195 # (This is the spec_dropout value, but ResNet has its own dropout)

# --- Fusion Head (MLP) ---
fusion_head_config:
  ts_feature_dim: 128
  hidden_dim: 512
  dropout: 0.4072201111436038

# --- Augmentations & Regularization ---
# NOTE: These are the tuned values from the Optuna study
mixup_alpha: 0.5634918462738934
channel_dropout_p: 0.4995010653284972
time_mask_p: 0.11136596286195871
time_mask_frac: 0.21484836239038596
freq_mask_p: 0.071204365
freq_mask_frac: 0.1116643980007393