# Base configuration for the Dual-Stream CNN using 4-fold CV on the "all_trials" dataset.
# UPDATED to support dynamic data loading and configurable spectrogram architectures.
model_name: dual_stream

# --- Data Loading ---
# The dataset directory is now constructed dynamically.
# Optuna will vary `dataset_name` and `spec_config_name`.
dataset_dir_base: "data_dual_stream" 
dataset_name: "all_trials_dataset"  # Default to all_trials for this config file
spec_config_name: "128-16"         # A sensible default
in_memory: true
n_folds: 4

# --- Training ---
batch_size: 32
lr: 1.0e-4
epochs: 100
early_stop: 15

# --- Time-Series Stream (MultiScaleCNN) ---
ts_stream_config:
  kernel_sizes: [7, 11, 15, 19]
  F1: 8
  F2: 16
  D: 2
  kernel_2: 16
  dropout: 0.5

# --- Spectrogram Stream (2D CNN) ---
spec_stream_config:
  # 'custom' for our original CNN, or 'resnet18' for transfer learning.
  arch: "custom" 
  # For pre-trained models, whether to use ImageNet weights.
  pretrained: true 
  # For the 'custom' arch, specifies channel sizes. Ignored for others.
  channels: [32, 64]

# --- Fusion Head (MLP) ---
fusion_head_config:
  ts_feature_dim: 128
  hidden_dim: 256
  dropout: 0.5

# --- Augmentations (applied only to the time-series) ---
shift_p: 0.5
scale_p: 0.1
noise_p: 0.3
noise_std: 0.02
mixup_alpha: 0.2
time_mask_p: 0.1
chan_mask_p: 0.1
