# Base configuration for the Dual-Stream CNN using 4-fold CV on the "acc_1 (45hz)" dataset.
# This file is ready to be used with optuna_space_dual_stream_acc1_v2.yaml
model_name: dual_stream

# --- Data Loading ---
# The dataset directory is constructed dynamically.
# Optuna varies `spec_config_name`; we fix `dataset_name` to the 45hz variant.
dataset_dir_base: "data_dual_stream"
dataset_name: "acc_1_dataset (45hz)"
spec_config_name: "128-16"   # default; Optuna will override
in_memory: true
n_folds: 4

# Tag used only for run-folder naming in Optuna (does not affect loading)
dataset_dir: "acc1_45hz_nf4"

# --- Training ---
batch_size: 32
lr: 1.0e-4
epochs: 100
early_stop: 15

# --- Time-Series Stream (MultiScaleCNN) ---
ts_stream_config:
  kernel_sizes: [7, 11, 15, 19]
  F1: 8
  F2: 16
  D: 2
  kernel_2: 16
  dropout: 0.5

# --- Spectrogram Stream (2D CNN) ---
spec_stream_config:
  arch: "custom"
  pretrained: true
  channels: [32, 64]

# --- Fusion Head (MLP) ---
fusion_head_config:
  ts_feature_dim: 128
  hidden_dim: 256
  dropout: 0.5

# --- Augmentations (applied only to the time-series) ---
shift_p: 0.5
scale_p: 0.1
noise_p: 0.3
noise_std: 0.02
mixup_alpha: 0.2
time_mask_p: 0.1
chan_mask_p: 0.1


