# FILE: dual_stream_base_acc1_t025.yaml
# LOSO configuration for a top model from study landing_digit_dual_stream-acc1-nf4-03.
# Original Trial ID: 25
# Mean Accuracy (nf4): 26.41%

model_name: dual_stream

# --- Data Loading ---
dataset_dir_base: "data_dual_stream"
dataset_name: "acc_1_dataset (45hz corrected)"
spec_config_name: "128-16"
in_memory: true

# --- Training ---
batch_size: 8
lr: 0.000143321
epochs: 100
early_stop: 15
scheduler_patience: 10 # This was tuned

# --- Time-Series Stream (MultiScaleCNN) ---
ts_stream_config:
  kernel_sizes: [7, 11, 15, 19]
  F1: 4
  F2: 16 # This is the default, F2 = 2 * F1
  D: 4
  kernel_2: 16
  dropout: 0.553144965

# --- Spectrogram Stream (2D CNN) ---
spec_stream_config:
  arch: "custom"
  pretrained: true # (Ignored for custom arch)
  channels: [32, 64]
  dropout: 0.22615034690872027 # (Used by custom arch)

# --- Fusion Head (MLP) ---
fusion_head_config:
  ts_feature_dim: 128
  hidden_dim: 128
  dropout: 0.3727295500866255

# --- Augmentations & Regularization ---
# NOTE: These are the tuned values from the Optuna study
mixup_alpha: 0.4755542059109222
channel_dropout_p: 0.46449345003077797
time_mask_p: 0.1577253205973096
time_mask_frac: 0.18882004221401513
freq_mask_p: 0.36907453743372814
freq_mask_frac: 0.18016920241810327