# FILE: dual_stream_base_acc1_t077.yaml
# LOSO configuration for a top model from study landing_digit_dual_stream-acc1-nf4-03.
# Original Trial ID: 77
# Mean Accuracy (nf4): 26.74%

model_name: dual_stream

# --- Data Loading ---
dataset_dir_base: "data_dual_stream"
dataset_name: "acc_1_dataset"
spec_config_name: "128-16"
in_memory: true

# --- Training ---
batch_size: 8
lr: 0.000382176
epochs: 100
early_stop: 15
scheduler_patience: 10 # This was tuned

# --- Time-Series Stream (MultiScaleCNN) ---
ts_stream_config:
  kernel_sizes: [7, 11, 15, 19]
  F1: 4
  F2: 16 # This is the default, F2 = 2 * F1
  D: 4
  kernel_2: 16
  dropout: 0.6059801373083967

# --- Spectrogram Stream (2D CNN) ---
spec_stream_config:
  arch: "custom"
  pretrained: true # (Ignored for custom arch)
  channels: [32, 64]
  dropout: 0.20447447720124748 # (Used by custom arch)

# --- Fusion Head (MLP) ---
fusion_head_config:
  ts_feature_dim: 128
  hidden_dim: 512
  dropout: 0.3325620026803647

# --- Augmentations & Regularization ---
# NOTE: These are the tuned values from the Optuna study
mixup_alpha: 0.44296295128423985
channel_dropout_p: 0.070482606
time_mask_p: 0.069217556
time_mask_frac: 0.20222630936705685
freq_mask_p: 0.3385027419513853
freq_mask_frac: 0.20135810562048367