# EEGNeX on raw EEG (30 Hz) – Base config for V2 augmentation tuning.
# ARCHITECTURE: FIXED to the champion model from the first study (Trial 24).
# DATASET: all_trials_dataset, which produced the best LOSO results.
# This file is designed to be used with optuna_space_eegnex_augmentations_v2.yaml.

model_name: eegnex

# --- Data Loading ---
dataset_dir: "data_preprocessed/all_trials_dataset (30hz)"
n_folds: 4 # Use 4-fold CV for a fast and efficient search

# --- Training (for fast search) ---
epochs: 40
early_stop: 10

# --- FIXED Hyperparameters from Architecture Champion (Trial 24) ---
batch_size: 8
lr: 0.0007775839158165456
scheduler_patience: 9
filter_1: 16
depth_multiplier: 1
drop_prob: 0.41118404993852475
kernel_block_1_2: 32

# --- FIXED Base Architectural Parameters ---
filter_2: 32
kernel_block_4: 16
dilation_block_4: 2
avg_pool_block4: 4
kernel_block_5: 16
dilation_block_5: 4
avg_pool_block5: 8
max_norm_conv: 1.0
max_norm_linear: 0.25

# --- Placeholder Augmentations (These will be overridden by Optuna) ---
mixup_alpha: 0.2
shift_p: 0.5
shift_min_frac: 0.0
shift_max_frac: 0.02
scale_p: 0.1
scale_min: 0.9
scale_max: 1.1
noise_p: 0.3
noise_std: 0.02
time_mask_p: 0.1
time_mask_frac: 0.1
chan_mask_p: 0.1
chan_mask_ratio: 0.05