# --- Select and configure the new EEGNetWithSE model ---
model_name: eegnet_se
se_reduction_ratio: 4 # Key parameter for the SE block's bottleneck.

dataset_dir: data_preprocessed/acc_1_dataset

batch_size: 64
lr: 1.0e-4
epochs: 100
early_stop: 15

# Augmentations (kept standard for baseline)
shift_p: 0.5
shift_min_frac: 0.005
shift_max_frac: 0.04
scale_p: 0.5
scale_min: 0.9
scale_max: 1.1
noise_p: 0.3
noise_std: 0.02