# EEGNeX on raw EEG (30 Hz) – Base config for the Consolidated Optuna Study.
# This file FIXES the "solved" parameters and uses fast-search settings.
# It is designed to be used with optuna_space_eegnex_consolidated.yaml.

model_name: eegnex

# --- Data Loading ---
dataset_dir: "data_preprocessed/all_trials_dataset (30hz)"
n_folds: 4 # WHY: Use 4-fold CV for a fast and efficient search.

# --- Training (for fast search) ---
epochs: 40
early_stop: 10

# --- FIXED Architectural Parameters (from Trial 24) ---
# These were the clear winners from the first study and are now fixed.
batch_size: 8
depth_multiplier: 1
kernel_block_1_2: 32

# --- FIXED Augmentation "Strength" Parameters (from Trial 217) ---
# These are not being tuned in the consolidated search, so we use the best
# values we found in the dedicated augmentation study.
shift_max_frac: 0.039063018
scale_p: 0.081532162
scale_max: 1.14987267
noise_p: 0.087185426
noise_std: 0.020216591
time_mask_frac: 0.086952604

# --- PLACEHOLDER values for Tuned Parameters ---
# Optuna will overwrite these values. They are here for completeness.
lr: 0.0007
scheduler_patience: 9
filter_1: 16
drop_prob: 0.4
mixup_alpha: 0.2
chan_mask_p: 0.4
time_mask_p: 0.3

# --- FIXED Base Model Parameters ---
filter_2: 32
kernel_block_4: 16
dilation_block_4: 2
avg_pool_block4: 4
kernel_block_5: 16
dilation_block_5: 4
avg_pool_block5: 8
max_norm_conv: 1.0
max_norm_linear: 0.25
shift_p: 0.5 # We can keep the probability high and let the amount (shift_max_frac) be the key driver
scale_min: 0.9
chan_mask_ratio: 0.05