# Optuna search space for the new MultiScaleCNN model on the landing_digit task.
# This space is designed to tune both the model's architecture and the
# training/augmentation hyperparameters to find the optimal configuration.

# --- Model Architecture Parameters (Specific to MultiScaleCNN) ---
# These control the "shape" of the network itself.
F1:
  method: categorical
  choices: [16, 32]       # Number of filters in the initial temporal convolutions.

D:
  method: categorical
  choices: [2, 4]         # Depth multiplier for the spatial convolution block.

F2:
  method: categorical
  choices: [32, 64]       # Number of filters in the separable convolution block.

dropout:
  method: uniform
  low: 0.2
  high: 0.6               # A standard range for dropout regularization.

# --- Optimizer Parameters ---
lr:
  method: log_uniform
  low: 1.0e-6
  high: 1.0e-3

weight_decay:
  method: log_uniform
  low: 1.0e-6
  high: 1.0e-2

# --- Training ---
batch_size:
  # REFINEMENT: Focusing on smaller batch sizes which have consistently performed better.
  method: categorical
  choices: [16, 32]

# --- Augmentation & Regularisation (Crucial for preventing overfitting) ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.7

shift_p:
  method: uniform
  low: 0.5
  high: 1.0

scale_p:
  method: uniform
  low: 0.0
  high: 0.2

noise_std:
  method: uniform
  low: 0.0
  high: 0.05

time_mask_p:
  method: uniform
  low: 0.0
  high: 0.3

chan_mask_p:
  method: uniform
  low: 0.0
  high: 0.5