# Optuna search space for EEGNeX on landing_digit (45 Hz)

lr:
  method: log_uniform
  low: 1.0e-5
  high: 1.0e-3

batch_size:
  method: categorical
  choices: [8, 16, 32]

filter_1:
  method: categorical
  choices: [8, 16]

filter_2:
  method: categorical
  choices: [32, 64]

depth_multiplier:
  method: categorical
  choices: [1, 2]

drop_prob:
  method: uniform
  low: 0.3
  high: 0.7

kernel_block_1_2:
  method: categorical
  choices: [32, 64]

kernel_block_4:
  method: categorical
  choices: [8, 16, 32]

dilation_block_4:
  method: categorical
  choices: [1, 2, 4]

avg_pool_block4:
  method: categorical
  choices: [2, 4, 8]

kernel_block_5:
  method: categorical
  choices: [8, 16, 32]

dilation_block_5:
  method: categorical
  choices: [2, 4, 8]

avg_pool_block5:
  method: categorical
  choices: [4, 8, 16]


