# File: configs/landing_digit/optuna_space_dual_stream_v2.yaml

# --- Data Representation ---
spec_config_name:
  method: categorical
  choices: ["128-16", "128-32", "64-8", "256-32"]

# --- Optimizer Parameters ---
lr:
  method: log_uniform
  low: 1.0e-5
  high: 1.0e-3
scheduler_patience:
  method: int
  low: 4
  high: 10

# --- Training ---
batch_size:
  method: categorical
  choices: [8, 16, 32]

# --- Architecture Search ---
spec_arch:
  method: categorical
  choices: ["custom", "resnet18"]

# --- Time-Series Stream (MultiScaleCNN) ---
ts_F1:
  method: categorical
  choices: [4, 8]
ts_D:
  method: categorical
  choices: [4, 6]
ts_dropout:
  method: uniform
  low: 0.2
  high: 0.7

# --- Spectrogram Stream (Custom CNN only) ---
# Note: spec_dropout is only applied when spec_arch is 'custom'.
spec_dropout:
  method: uniform
  low: 0.1
  high: 0.5

# --- Fusion Head (MLP) ---
fusion_hidden_dim:
  method: categorical
  choices: [128, 256, 512]
fusion_dropout:
  method: uniform
  low: 0.3
  high: 0.7

# --- Augmentation & Regularization ---
# For the Time-Series Stream
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.6
channel_dropout_p:
  method: uniform
  low: 0.0
  high: 0.5

# For the Spectrogram Stream (SpecAugment)
time_mask_p:
  method: uniform
  low: 0.0
  high: 0.5
time_mask_frac:
  method: float
  low: 0.05
  high: 0.25
freq_mask_p:
  method: uniform
  low: 0.0
  high: 0.5
freq_mask_frac:
  method: float
  low: 0.05
  high: 0.25
