# Optuna search space for landing-digit task (ViT engine)
# Copied from legacy vit/optuna_space_vit.yaml

lr:
  method: log_uniform
  low: 3e-5
  high: 1.5e-3

weight_decay:
  method: log_uniform
  low: 1e-6
  high: 1e-2

dropout:
  method: uniform
  low: 0.0
  high: 0.2

mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.6

time_mask_p:
  method: uniform
  low: 0.0
  high: 0.5

freq_mask_p:
  method: uniform
  low: 0.0
  high: 0.5

drop_path_rate:
  method: uniform
  low: 0.0
  high: 0.2

attn_drop_rate:
  method: uniform
  low: 0.0
  high: 0.15

token_drop_rate:
  method: uniform
  low: 0.0
  high: 0.3

qkv_bias:
  method: categorical
  choices: [true, false]

label_smoothing:
  method: uniform
  low: 0.0
  high: 0.2

betas:
  method: uniform
  low: 0.92
  high: 0.999

grad_clip_norm:
  method: categorical
  choices: [0.5, 1.0, 2.0]

min_lr:
  method: log_uniform
  low: 1e-7
  high: 5e-6

time_mask_frac:
  method: uniform
  low: 0.05
  high: 0.20

freq_mask_frac:
  method: uniform
  low: 0.05
  high: 0.20 