# Optuna search space for EEGNeX augmentations.
# This search is performed on a fixed, high-performing architecture.

# --- MixUp Regularization ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.5

# --- Channel Masking ---
chan_mask_p:
  method: uniform
  low: 0.0
  high: 0.4

# --- Time Masking ---
time_mask_p:
  method: uniform
  low: 0.0
  high: 0.4
time_mask_frac:
  method: float
  low: 0.05
  high: 0.25

# --- Gaussian Noise ---
noise_p:
  method: uniform
  low: 0.0
  high: 0.5

# --- Time Shifting (Jitter) ---
shift_p:
  method: uniform
  low: 0.0
  high: 0.5