# Optuna search space for EEGNeX on landing_digit (30 Hz)
# This is a focused search on the most impactful parameters for the initial study.

lr:
  method: log_uniform
  low: 1.0e-4
  high: 1.0e-3

batch_size:
  method: categorical
  choices: [8, 16]

scheduler_patience:
  method: int
  low: 8
  high: 12

# --- Core EEGNeX Architecture ---
filter_1:
  method: categorical
  choices: [8, 16] # Number of initial temporal filters

kernel_block_1_2:
  method: categorical
  choices: [32, 64] # Kernel size of the first two temporal convs

depth_multiplier:
  method: categorical
  choices: [1, 2] # Depth multiplier for the spatial convolution

drop_prob:
  method: uniform
  low: 0.3
  high: 0.7