# Optuna search space for EEGNeX (Consolidated)
# This search combines the most impactful architecture and augmentation parameters
# using refined ranges based on all previous studies.

# --- Core Architectural Parameters ---
lr:
  method: log_uniform
  low: 5.0e-4
  high: 9.0e-4 # Best results were in this higher range
scheduler_patience:
  method: int
  low: 8
  high: 11
filter_1:
  method: categorical
  choices: [8, 16] # Both showed promise
drop_prob:
  method: uniform
  low: 0.3
  high: 0.7

# --- Core Augmentation Parameters ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.5
chan_mask_p:
  method: uniform
  low: 0.3
  high: 0.7 # EXPANDED: Best results clustered at the high end of the last search
time_mask_p:
  method: uniform
  low: 0.2
  high: 0.5 # REFINED: Best results were in this strong middle/high range