lr:
  method: log_uniform
  low: 1e-6
  high: 1e-2
steps:
  method: categorical
  choices: [1, 2, 3]
test_batch:
  method: categorical
  choices: [8, 16, 32, 64]
t:
  method: uniform
  low: 0.5
  high: 2.0
align:
  method: categorical
  choices: [true]
stride:
  method: categorical
  choices: [1, 4, 8] 