# Optuna search space for the EEGNetWithSE model on the landing_digit task.
# This is a comprehensive search space designed to tune all key
# architectural, optimizer, and regularization hyperparameters.

# --- Optimizer Parameters ---
lr:
  method: log_uniform
  low: 1.0e-5
  high: 1.0e-3

# --- Model Hyperparameters ---
# These are specific to the EEGNetWithSE architecture
dropout:
  method: uniform
  low: 0.2
  high: 0.8
se_reduction_ratio:
  method: categorical
  choices: [2, 4, 8, 16]

# --- Training ---
# Added batch_size to the search as it has proven to be an impactful parameter.
batch_size:
  method: categorical
  choices: [16, 32]

# --- Augmentation Probabilities ---
shift_p:
  method: uniform
  low: 0.3
  high: 1.0
scale_p:
  method: uniform
  low: 0.0
  high: 1.0
noise_p:
  method: uniform
  low: 0.0
  high: 1.0
noise_std:
  method: uniform
  low: 0.01
  high: 0.1

# --- Masking and Mixup (Regularization) ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.7
time_mask_p:
  method: uniform
  low: 0.0
  high: 0.5
time_mask_frac:
  method: uniform
  low: 0.05
  high: 0.25
chan_mask_p:
  method: uniform
  low: 0.0
  high: 0.5
chan_mask_ratio:
  method: uniform
  low: 0.05
  high: 0.25
channel_dropout_p:
  method: uniform
  low: 0.0
  high: 0.5