# Vision-Transformer specific base config for landing-digit task
# Uses pre-computed 128×128 CWT spectrogram tensors.

dataset_dir: data_spectrograms/landing_digit_cwt_128x128

# Training hyper-parameters (can be tuned later via Optuna)
batch_size: 32
lr: 0.0003
epochs: 100
early_stop: 10

img_size: 128
model_name: vit_relpos_medium_patch16_224
domain_adapter: true 