# Optuna search space for EEGNeX on the CROPPED 1-3 task - STAGE 3
# This is the final tuning stage, focusing on finding the best regularization
# strategy for our champion architecture.

# --- MixUp Regularization ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.5

# --- Channel Masking ---
chan_mask_p:
  method: uniform
  low: 0.2
  high: 0.7 # A wide range is good, as this is a powerful regularizer

# --- Time Masking ---
time_mask_p:
  method: uniform
  low: 0.2
  high: 0.5
time_mask_frac:
  method: float
  low: 0.05
  high: 0.3 # Allow for slightly larger masks on this short signal

# --- Gaussian Noise ---
noise_p:
  method: uniform
  low: 0.0
  high: 0.5
noise_std:
  method: float
  low: 0.01
  high: 0.05

# --- Time Shifting (Jitter) ---
shift_p:
  method: uniform
  low: 0.0
  high: 0.5
shift_max_frac:
  method: float
  low: 0.01
  high: 0.08 # Allow for a slightly larger shift percentage

# --- Amplitude Scaling ---
scale_p:
  method: uniform
  low: 0.0
  high: 0.3
scale_max:
  method: float
  low: 1.1
  high: 1.2