# "Leak-Free Champion" Configuration for EEGNeX on 45Hz Cardinality Data
# This file represents the best model found from the Stage 1 search (as of now),
# selected based on the INNER VALIDATION accuracy.
# ARCHITECTURE: From Trial 575.
# DATASET: all_trials_dataset (1-45hz)
# EVALUATION: Full Leave-One-Subject-Out (LOSO)

model_name: eegnex

# --- Data Loading ---
dataset_dir: "data_preprocessed/all_trials_dataset (1-45hz) V2"
use_channel_list: non_scalp
crop_ms: [] # Using the full time window

# --- Training (for final LOSO run) ---
epochs: 100
early_stop: 20
save_ckpt: true

# --- Hyperparameters from the True Champion (Trial 575) ---
lr: 0.000756221979000344
batch_size: 8
scheduler_patience: 11
filter_1: 8
kernel_block_1_2: 128
drop_prob: 0.767062997322734
depth_multiplier: 1

# --- Channel & Temporal Gates ---
channel_gate: true
gate_init: 1.0
gate_l1_lambda: 0.000132187892767351
temporal_gate: true
time_gate_init: 1.0
time_gate_l1_lambda: 0.000340739150116844
time_gate_tv_lambda: 0.00702837587946004

# --- FIXED Base Model & Augmentation Parameters ---
filter_2: 32
kernel_block_4: 16
dilation_block_4: 2
avg_pool_block4: 4
kernel_block_5: 16
dilation_block_5: 4
avg_pool_block5: 8
max_norm_conv: 1.0
max_norm_linear: 0.25
mixup_alpha: 0.3
shift_p: 0.2
shift_max_frac: 0.04
scale_p: 0.1
scale_max: 1.15
noise_p: 0.1
noise_std: 0.02
time_mask_p: 0.3
time_mask_frac: 0.1
chan_mask_p: 0.3
chan_mask_ratio: 0.05