# "Ultimate Champion" Configuration for EEGNeX on 45Hz Data
# This file mirrors the style of existing LOSO configs but targets the
# cardinality_1_3 task (Conditions: 11, 22, 33). crop_ms is disabled ([]).

model_name: eegnex

# --- Data Loading ---
dataset_dir: "data_preprocessed/all_trials_dataset (1-45hz) V2"
use_channel_list: non_scalp
include_channels: []
xai_top_k_channels: 30
crop_ms: []
# No n_folds key defaults the runner to full Leave-One-Subject-Out (LOSO)

# --- Training (for final LOSO run) ---
epochs: 100
early_stop: 20
save_ckpt: true

# --- Hyperparameters (copy of strong baseline) ---
lr: 0.00119596743567463
batch_size: 16
scheduler_patience: 13
filter_1: 24
kernel_block_1_2: 16
drop_prob: 0.480132586724977
depth_multiplier: 1

# Deeper Architecture
kernel_block_4: 24
dilation_block_4: 1
avg_pool_block4: 4
kernel_block_5: 8
dilation_block_5: 4
avg_pool_block5: 16

# Augmentations
mixup_alpha: 0.167943267
shift_p: 0.182100037
shift_max_frac: 0.039063018
scale_p: 0.081532162
scale_max: 1.14987267
noise_p: 0.087185426
noise_std: 0.020216591
time_mask_p: 0.340388497
time_mask_frac: 0.086952604
chan_mask_p: 0.332160404

# --- FIXED Base Model Parameters ---
filter_2: 32
max_norm_conv: 1.0
max_norm_linear: 0.25
scale_min: 0.9
chan_mask_ratio: 0.05


# --- Channel Gate (for LOSO baseline; can be disabled if desired) ---
channel_gate: true
gate_init: 1.0
gate_l1_lambda: 0.0002


# --- Temporal Gate (optional) ---
temporal_gate: true
time_gate_init: 1.0
time_gate_l1_lambda: 0.0002
time_gate_tv_lambda: 0.0001
