# Optuna search space for EEGNeX on the Cardinality 1-3 task - STAGE 1
# This search uses wide, exploratory ranges to find the optimal core model
# for this new type of data.

# --- Optimizer and Training Parameters ---
lr:
  method: log_uniform
  low: 1.0e-4
  high: 1.5e-3 # WIDE RANGE: The optimal LR is unknown.
batch_size:
  method: categorical
  choices: [8, 16, 32] # WIDE RANGE: The optimal batch size is unknown.
scheduler_patience:
  method: int
  low: 8
  high: 15 # WIDE RANGE: The learning dynamics are unknown.

# --- Core EEGNeX Architectural Parameters ---
filter_1:
  method: categorical
  choices: [8, 16, 24, 32] # WIDE RANGE: Test if the model needs more or less capacity.
kernel_block_1_2:
  method: categorical
  choices: [32, 64, 128] # WIDE RANGE: The optimal temporal filter size is unknown.
drop_prob:
  method: uniform
  low: 0.3
  high: 0.8 # WIDE RANGE: The optimal regularization is unknown.

# --- Channel Gate Regularization ---
gate_l1_lambda:
  method: log_uniform
  low: 1.0e-5
  high: 5.0e-4