# Optuna search space for EEGNeX on the 1-3 task - STAGE 1: Architecture Search
# This search focuses on finding the optimal core model for the small-number dataset.

# --- Optimizer and Training Parameters ---
lr:
  method: log_uniform
  low: 5.0e-4
  high: 1.2e-3 # Start with a range that has proven effective.
batch_size:
  method: categorical
  choices: [8, 16] # A smaller dataset might favor a smaller batch size.
scheduler_patience:
  method: int
  low: 8
  high: 14 # Patience is likely still very important.

# --- Core EEGNeX Architectural Parameters ---
filter_1:
  method: categorical
  choices: [8, 16, 24] # Test if a narrower filter is better for a simpler problem.
kernel_block_1_2:
  method: categorical
  choices: [64, 128] # Test if the long kernel is still optimal.
drop_prob:
  method: uniform
  low: 0.3
  high: 0.7 # Less data may require more dropout.